### ISSUE TITLE
cover.jpg wrong image extension

### ISSUE THREAD

**Issue by kotzer3** [ptrstn/dailyblink#29]
**Version of dailyblink**: 1.1.1
**Python version**:  3.9.2
**Operating system**:  debian 11 (bullseye) 5.10.92-1 armv7l

```
root@banane:~# python3 -m dailyblink --version
__main__.py 1.1.1
root@banane:~# python3 --version
Python 3.9.2
root@banane:~# uname -a
Linux banane.oben.lan 5.10.0-11-armmp-lpae #1 SMP Debian 5.10.92-1 (2022-01-18) armv7l GNU/Linux
```
just a cosmetic thing (because i use irfanview with plugins to display images)
the cover.jpg is not always a jpg.
german blink:
2022-03-10 it was a png
2022-03-11 it was a webp file
2022-03-08 it was a png

![2022-03-11 09_49_03-Window](https://user-images.githubusercontent.com/33086409/157834318-f6390fde-eedd-480d-886d-2029a69f3be1.png)

**Comment by ptrstn** [comment]
Hm, that's weird indeed.

Same thing with the current [Daily Blink](https://www.blinkist.com/de/nc/daily):

The image url is: https://images.blinkist.io/images/books/5e48b5726cee070006209356/1_1/470.jpg


![image](https://user-images.githubusercontent.com/28670760/157835798-0e6ad565-bd52-4079-b56a-9e62b83729b9.png)

However, when saving this image to the local file system, it turns out that it isn't JPEG after all:

```console
wget https://images.blinkist.io/images/books/5e48b5726cee070006209356/1_1/470.jpg
```

```
--2022-03-11 10:06:41--  https://images.blinkist.io/images/books/5e48b5726cee070006209356/1_1/470.jpg
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving images.blinkist.io (images.blinkist.io)... 104.18.16.118, 104.18.17.118, 2606:4700::6812:1076, ...
Connecting to images.blinkist.io (images.blinkist.io)|104.18.16.118|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 86108 (84K) [image/png]
Saving to: '470.jpg'

470.jpg             100%[===================>]  84.09K  --.-KB/s    in 0.008s  

2022-03-11 10:06:41 (9.69 MB/s) - '470.jpg' saved [86108/86108]
```

```console
file 470.jpg
```

```
470.jpg: PNG image data, 470 x 470, 8-bit/color RGBA, non-interlaced
```

Not sure yet how to prevent this behavior.

**Comment by kotzer3** [comment]
So this is related to blinkist... maybe you fix their problem or we leave it as it is.. I can live with it :)

**Comment by kotzer3** [comment]
On my screen in first post, bottom left corner. Irfanview says it is webp.. I had to install plug-ins package for irfanview to display..

I redownloaded, now it is a png.. 
attached the backed up file from this morning 9:17..

**Comment by ptrstn** [comment]
> sry, but what exact steps are needed to run the blinkist from the developer branch? I want to help and check.. (i am not so familar with python and git in detail -.-)

```console
pip install --upgrade git+https://github.com/ptrstn/dailyblink@develop
```

**Comment by kotzer3** [comment]
i would say, you fixed it - I am fine with it :)
```
root@banane:~# ls -alGh /srv/dev-disk-by-label-MyDrive/music/blinks/german/2022-03-12\ -\ Vegan\ ist\ Unsinn/
total 23M
drwxrwxrwx 1 root 1.8K Mar 12 20:21  .
drwxrwxrwx 1 root  12K Mar 12 09:17  ..
-rwxrwxrwx 1 root 1.1M Mar 12 20:21 '00 - Vegan ist Unsinn.m4a'
-rwxrwxrwx 1 root 2.9M Mar 12 20:21 '01 - Vegan ist Unsinn.m4a'
-rwxrwxrwx 1 root 3.1M Mar 12 20:21 '02 - Vegan ist Unsinn.m4a'
-rwxrwxrwx 1 root 2.8M Mar 12 20:21 '03 - Vegan ist Unsinn.m4a'
-rwxrwxrwx 1 root 2.8M Mar 12 20:22 '04 - Vegan ist Unsinn.m4a'
-rwxrwxrwx 1 root 2.7M Mar 12 20:22 '05 - Vegan ist Unsinn.m4a'
-rwxrwxrwx 1 root 2.9M Mar 12 20:22 '06 - Vegan ist Unsinn.m4a'
-rwxrwxrwx 1 root 3.0M Mar 12 20:22 '07 - Vegan ist Unsinn.m4a'
-rwxrwxrwx 1 root 1.2M Mar 12 20:22 '08 - Vegan ist Unsinn.m4a'
-rwxrwxrwx 1 root  23K Mar 12 20:21 'Vegan ist Unsinn - Niko Rittenau Patrick Schönfeld Ed Winters.md'
-rwxrwxrwx 1 root  50K Mar 12 09:17  cover.jpg
-rwxrwxrwx 1 root  50K Mar 12 20:21  cover.webp
-rwxrwxrwx 1 root  233 Mar 12 20:22  playlist.m3u
root@banane:~# python3 -m dailyblink --version
__main__.py 1.2.0
root@banane:~#
```
as you can see, the file from the morning 9:17 (daily cron) is still jpg, after upgrade to 1.2.0 recently at 20:21 the cover is a webp.
