### ISSUE TITLE
todays run exits with error (and no dls)

### ISSUE THREAD

**Issue by kotzer3** [ptrstn/dailyblink#3]
`[tbr@tbr-fedora ~]$ dailyblink 
Downloading the free daily Blinks...

english (en):
The Internet of Us - Michael Patrick Lynch

Traceback (most recent call last):
  File "/home/tbr/.local/bin/dailyblink", line 33, in <module>
    sys.exit(load_entry_point('dailyblink==0.5.1', 'console_scripts', 'dailyblink')())
  File "/home/tbr/.local/lib/python3.9/site-packages/dailyblink/blinks.py", line 159, in main
    blink = request_blinkist_book_text(blink_url)
  File "/home/tbr/.local/lib/python3.9/site-packages/dailyblink/blinks.py", line 51, in request_blinkist_book_text
    book_id = soup.find_all("div", {"class": "reader__container"})[0]["data-book-id"]
IndexError: list index out of range
[tbr@tbr-fedora ~]$ uname -a
Linux tbr-fedora 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[tbr@tbr-fedora ~]$ `

on the website itself everything looks as usual.. any ideas?

**Comment by kotzer3** [comment]
Today everything back fine again. Maybe some special char issues?

for reference:
`[tbr@tbr-fedora ~]$ dailyblink 
Downloading the free daily Blinks...

english (en):
It's All Possible - Rob Hartnett

Saving book text...
Saving book cover...
Saving audio track #1 - What’s in it for me? An optimistic guide...
Saving audio track #2 - Life is about believing in possibility, ...
Saving audio track #3 - Nothing is possible without a positive m...
Saving audio track #4 - Stay motivated by finding and pursuing y...
Saving audio track #5 - Develop a strategy to make your vision a...
Saving audio track #6 - Put your plans into action with the CHAM...
Saving audio track #7 - Never stop developing your skills and kn...
Saving audio track #8 - Final summary...

german (de):
Die Ordnung der Zeit - Carlo Rovelli

Saving book text...
Saving book cover...
Saving audio track #1 - Was drin ist für dich: Eine wilde Entdec...
Saving audio track #2 - Zeit ist nicht gleich Zeit...
Saving audio track #3 - Wer rastet, rostet schneller...
Saving audio track #4 - Die Zeit vergeht nicht nahtlos, sondern ...
Saving audio track #5 - Adieu Gegenwart!...
Saving audio track #6 - Ich welke, also werde ich älter...
Saving audio track #7 - Die Sonne als Motor der Zeit...
Saving audio track #8 - Ich denke Zeit, also bin ich...
Saving audio track #9 - Fazit...

All blinks were saved under /home/tbr/Musik/blinks
[tbr@tbr-fedora ~]$`

**Comment by ptrstn** [comment]
Hm, if this happens again, please let me know! 
At the moment I can't find the problem.

**Comment by kotzer3** [comment]
closed - because of one-time-issue. will re-open if needed
