### ISSUE TITLE
Suggestion: add m3u 

### ISSUE THREAD

**Issue by ManuelSchneid3r** [ptrstn/dailyblink#4]
Hi, thank you for this nifty tool. I have a suggestion. Sometimes media players suck and having around a m3u would be nice.
Could you please also generate a m3u playlist? It's as  simple as that in the output dir `find . -iname "*.m4a" | sort > playlist.m3u` but ofc a native solution would be nicer. Regards

**Comment by ptrstn** [comment]
Hello,
Thanks for your suggestion! 
That does sound good. Will look into that once i find some time :-)

**Comment by ManuelSchneid3r** [comment]
See #5
